config/routes.rb
Supermarket::Application.routes.draw do

  devise_for :users

  devise_for :installs

  scope "(:clientType)" do 
    resources :offers do
      member do
        get :remove_product
        get :add_product
      end
    end

    resources :branches

    resources :categories do
      member do
        get :remove_product
        get :add_product
      end
    end

    resources :products do
      member do
        get :list_offers
      end
    end
    resources :users

    root :to => 'offers#index'

    match 'offer/test' =>  'offers#test_requests'
  end

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  attr_accessible :address, :name
  has_and_belongs_to_many :categories
  has_many :products, through: :categories
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @branches }
    end
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
    @branch = Branch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @branch }
    end
  end

  # GET /branches/new
  # GET /branches/new.json
  def new
    @branch = Branch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @branch }
    end
  end

  # GET /branches/1/edit
  def edit
    @branch = Branch.find(params[:id])
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(params[:branch])

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render json: @branch, status: :created, location: @branch }
      else
        format.html { render action: "new" }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /branches/1
  # PUT /branches/1.json
  def update
    @branch = Branch.find(params[:id])

    respond_to do |format|
      if @branch.update_attributes(params[:branch])
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch = Branch.find(params[:id])
    @branch.destroy

    respond_to do |format|
      format.html { redirect_to branches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editing branch</h1>

<%= render 'form' %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
<h1>Listing branches</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @branches.each do |branch| %>
  <tr>
    <td><%= branch.name %></td>
    <td><%= branch.address %></td>
    <td><%= link_to 'Show', branch %></td>
    <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
    <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Branch', new_branch_path %>

app/views/branches/new.html.erb
<h1>New branch</h1>

<%= render 'form' %>

<%= link_to 'Back', branches_path %>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @branch.name %>
</p>

<p>
  <b>Address:</b>
  <%= @branch.address %>
</p>


<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>