config/routes.rb
Supermarket::Application.routes.draw do

  devise_for :users

  devise_for :installs

  scope "(:clientType)" do 
    resources :offers do
      member do
        get :remove_product
        get :add_product
      end
    end

    resources :branches

    resources :categories do
      member do
        get :remove_product
        get :add_product
      end
    end

    resources :products do
      member do
        get :list_offers
      end
    end
    resources :users

    root :to => 'offers#index'

    match 'offer/test' =>  'offers#test_requests'
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price

  validates :name, presence: true
  validates :description, presence: true
  validates_numericality_of :price,greater_than: 0



  has_and_belongs_to_many :categories

  has_many :offer_products
  has_many :offers, through: :offer_products



  def branches
    branches = {}
    self.categories.each do |cat|
      branches[cat] = cat.branches
    end
    return branches
  end

  def has_offer
    !self.offers.empty?
  end

  def price_of_offer offer_id
    price = OfferProduct.where({product_id: self.id,offer_id: offer_id}).first.try :offer_price
    price.nil? ?  Product.find(self.id).price : price.round(2)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @offers = @product.offers
  end

  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to "/products/#{@product.id}", notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new"}
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to "/products/#{@product.id}", notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit"}
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_path}
      format.js
      format.json { head :no_content }
    end
  end
  
  def list_offers
    @product = Product.find(params[:id])
    @offers = @product.offers
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
    <%= form_for(@product) do |f| %>
      <div class="form-item">
        <div class="item">
        <%= f.text_field :name,placeholder: "#{controller_name.singularize} name" %>
        </div>
        <%= f.error_message_on :name %>
        <div class="help">
          <%= "#{controller_name.singularize} name" %>
        </div>
      </div>
      <div class="form-item">
        <div class="item">
        <%= f.text_area :description ,rows: 5,placeholder: "#{controller_name.singularize} description" %>
        </div>
        <%= f.error_message_on :description %>
        <div class="help">
          <%= "#{controller_name.singularize} description" %>
        </div>
      </div>
      <div class="form-item">
        <div class="item input-prepend">
          <span class="add-on">$</span>
          <%= f.number_field :price,id: "prependedInput",placeholder: "#{controller_name.singularize} price " %>
        </div>
        <%= f.error_message_on :price %>
        <div class="help">
          <%= "#{controller_name.singularize} price " %>
        </div>
      </div>
      <div class="form-item">
        <div class="controls">
          <%= f.submit nil,class: "btn" %>
        </div>
      </div>
    <% end %>

app/views/products/_index.html.erb
<div id="products-list" >

    <% products.each do |product| %>
        <div id="product_<%= product.id %>" class="product unlink-text">
          <div class = " product-detail  main-detail">
            <span> <%= link_to truncate(product.name,length: 50),"/products/#{product.id}" ,class: "unlink-text",title: product.name  %></span> 
          </div>
          <div class = " product-detail  main-detail">
            <span> <%= link_to truncate(product.description,length: 70),"/products/#{product.id}",class: "unlink-text",title: product.description %>             </span>
          </div>
          <div class = " product-detail  secandary-detail">
            <span class="<%= 'old-price' if(controller_name == "offers" && action_name == "show")%>">
                <%= product.price %> $
            </span>
            <% if controller_name == "offers" && action_name == "show" %>
              <span class="offered-price">
                  <%= product.price_of_offer @offer.id %> $
              </span>
            <% end %>
          </div>
          <% if controller_name == "categories" && action_name=="show" %>
              <% no_of_offers = product.offers.count %>
              <div class = " product-detail  secandary-detail">
                <span>
                  <% if no_of_offers > 0 %>
                    <%= link_to "#{no_of_offers} Offers",list_offers_product_path({id: product.id}),remote: true,class: "unlink-text"  %>
                    
                  <% else %>
                     No Offers
                  <% end %>
                </span>
              </div>
          <% end %>


          <% if admin_user_signed_in? %>
              <% if controller_name == "offers" %>
                <% if action_name == "edit" && newbie == false %>
                  <%= link_to '<i class="icon-trash icon-white "></i>'.html_safe,"/offers/#{@offer.id}/remove_product?product_id=#{product.id}",class: " btn btn-small btn-inverse destroy",remote: true,title: "remove product form this offer "%>
                <% elsif  action_name == "edit" && newbie == true %>
                  <%= link_to '<i class="icon-ok icon-white "></i>'.html_safe,"/offers/#{@offer.id}/add_product?product_id=#{product.id}",class: " btn btn-small btn-success destroy",remote: true,title: "add product to this offer "%>
                <% end %>
              <% elsif controller_name == "categories" %>
                <% if action_name == "edit" && newbie == false %>
                  <%= link_to '<i class="icon-trash icon-white "></i>'.html_safe,"/categories/#{@category.id}/remove_product?product_id=#{product.id}",class: " btn btn-small btn-inverse destroy",remote: true,title: "remove product form this category "%>
                <% elsif  action_name == "edit" && newbie == true %>
                  <%= link_to '<i class="icon-ok icon-white "></i>'.html_safe,"/categories/#{@category.id}/add_product?product_id=#{product.id}",class: " btn btn-small btn-success destroy",remote: true,title: "add product to this category "%>
                <% end %>
              <% elsif controller_name == "products"%>
              <%= link_to '<i class="icon-trash icon-white"></i>'.html_safe,"/products/#{product.id}",method: :delete,remote: true,class: " btn btn-small btn-inverse destroy"%>
              <%= link_to '<i class="icon-edit "></i>'.html_safe,"/products/#{product.id}/edit",class: " btn btn-small  edit"%>
              <% end %>
          <% end %>
        </div>
    <% end %>

</div>

app/views/products/destroy.js.erb
$('#product_<%="#{@product.id}"%>').fadeOut(800);

app/views/products/edit.html.erb
<div id='product-form' class="round-top-corners">

  <p class="form-head-text"><%= "update #{controller_name.singularize}" %></p>
  <%= render 'form' %>
</div>

app/views/products/index.html.erb
<% if @products.any?  %>
  <%= render 'products/index' , products: @products%>
<% else %>
    <p class=" alert no-results"> there is no products added yet
      <button class="close" data-dismiss="alert">×</button>
    </p>
<% end %>
<% if admin_user_signed_in? %>
  <div class="index-actions">
      <%= link_to 'new product',new_product_path,class: 'btn'  %>
  </div>
<% end %>

app/views/products/list_offers.js.erb
$("#myModal .modal-body").html('<%=j render partial: "offers/index" %>');
$("#myModal").modal('show');

app/views/products/new.html.erb
<div id='product-form' class="round-top-corners">

  <p class="form-head-text"><%= "add new #{controller_name.singularize}" %></p>
  <%= render 'form' %>
</div>

app/views/products/show.html.erb
<div id='show-product' class=''>
     <div id='show-product-name' class='tooltipped unlink-text' data-content= "<%= @product.name %>">
            <%= truncate(@product.name,length: 35) %> 
     </div>
     <div id='show-product-desc' class='tooltipped unlink-text' data-content= "<%= @product.description %>">
            <%= truncate(@product.description,length:350)%>
    </div>
    <div id="show-product-price">
        <%= [@product.price,"$"].join(" ") %> 
    </div>
    <div id="show-product-categories" class="tooltipped" data-content='<%= @product.categories.map(&:name).join(", ") %>'>
        <% if @product.categories.any? %>
                <%=truncate @product.categories.map(&:name).join(", "),length:30 %>
        <% else %>
                Uncategorized
        <% end %>
    </div>
</div>

<% if @offers.any? %>
    <%= render 'offers/index' %>
    
<% else %>
        <p class=" alert no-results"> this products is not included into any offers yet
            <button class="close" data-dismiss="alert">×</button>
        </p>
<% end %>

<% if admin_user_signed_in? %>
    <div class='show-actions'>
              <%= link_to 'edit product',"/products/#{@product.id}/edit",class: " btn "%>
              <%= link_to 'delete product',"/products/#{@product.id}",method: :delete,class: " btn btn-inverse "%>

    </div>
<% end %>