config/routes.rb
Supermarket::Application.routes.draw do

  devise_for :users

  devise_for :installs

  scope "(:clientType)" do 
    resources :offers do
      member do
        get :remove_product
        get :add_product
      end
    end

    resources :branches

    resources :categories do
      member do
        get :remove_product
        get :add_product
      end
    end

    resources :products do
      member do
        get :list_offers
      end
    end
    resources :users

    root :to => 'offers#index'

    match 'offer/test' =>  'offers#test_requests'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Supermarket" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%# favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%# favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%# favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%# favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%# favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Supermarket",root_path ,class: "brand unlink-text" %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li>  <%= link_to "Offers", offers_path,title: "browse offers"  %>             </li>
              <li>  <%= link_to "Products", products_path,title: "browse products"  %>       </li>
              <li>  <%= link_to "Categories", categories_path,title: "browse categories" %>  </li>
            </ul>
            <ul class ="nav pull-right">
              <% if user_signed_in? %>
                  <li> <%= link_to current_user.email, "/users/#{current_user.id}"  %></li>
                  <li>  <%= link_to "SignOut", destroy_user_session_path ,method: :delete%></li>
              <% else %>
                  <li> <%= link_to "SignIn", new_user_session_path  %></li>
                  <li> <%= link_to "SignUp", new_user_registration_path  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container main-body ">
            <%= bootstrap_flash %>
            <%= yield %>


      <footer class= "round-bottom-corners">
        <ul>
          <li> <a href="#">   About                                                </a> </li>
          <li> <a href="http://www.cubeegypt.com/home/contactus.php">  Contact US  </a> </li>
          <li> <a href="http://www.cubeegypt.com/">   &copy; CubeEgypt 2013        </a> </li>
        </ul>
      </footer>

        <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-header">
            <!-- <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> -->
            <h3 id="myModalLabel">Product offers</h3>
          </div>
          <div class="modal-body">
          </div>
          <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
          </div>
        </div>


    </div> <!-- /container -->
<script>
  $(document).ready(function(){
    $(".datepicker").datepicker({format: "dd/mm/yyyy",
                                  });
    $('.form-item .item').hover(
      function(){$(this).parent().find(".help").css('display','inline-block');},function(){$(this).parent().find(".help").fadeOut()});
    $(".offer,.product,.category").hover(function(){$(this).find(".destroy, .edit").fadeIn()},function(){$(this).find(".destroy, .edit").fadeOut()})
    $('.tooltipped').popover({trigger:"hover",placement: "bottom"});
    // offer products 
    $('#edit_offer_products').click(function(){
      $(this).parent().parent().find("div#edit-offer-add-products").hide();
      $(this).parent().parent().find("div#edit-offer-edit-products").slideDown(2000);
      $(this).hide();
      $("#collapse_offer_products").fadeIn();
      $("#collapse_add_offer_products").hide();
      $("#add_offer_products").fadeIn();
      
      return false;
    });
    $("#collapse_offer_products").click(function(){
      $(this).parent().parent().find("div#edit-offer-edit-products").slideUp();
      $(this).hide();
      $("#edit_offer_products").fadeIn();
      return false;
    });
    // add to offer products
    $('#add_offer_products').click(function(){
      $(this).parent().parent().find("div#edit-offer-edit-products").hide();
      $(this).parent().parent().find("div#edit-offer-add-products").slideDown(2000);
      $(this).hide();
      $("#collapse_add_offer_products").fadeIn();
      $("#collapse_offer_products").hide();
      $("#edit_offer_products").fadeIn();
      return false;
    });
    $("#collapse_add_offer_products").click(function(){
      $(this).parent().parent().find("div#edit-offer-add-products").slideUp();
      $(this).hide();
      $("#add_offer_products").fadeIn();
      return false;
    });
    
  });
</script>
  </body>

</html>